version: '3.9'

services:
  php:
    image: php:8.1-fpm-alpine
    container_name: php-lab
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: php-lab-nginx
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: php-lab-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phplabdb
      MYSQL_USER: phplabuser
      MYSQL_PASSWORD: Secret@12345
    ports:
      - '3306:3306'
    volumes:
      - ./php-lab-mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    container_name: php-lab-phpmyadmin
    image: phpmyadmin:5
    environment:
      - PMA_HOST=php-lab-mysql
      - PMA_USER=phplabuser
      - PMA_PASSWORD=Secret@12345
      - UPLOAD_LIMIT=100M
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      - app-network

networks:
  app-network:
